# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:

      ##CLONING REPOS##
      #clone applicant repo
      - checkout

      #clone moss, submissions, and jars. move jars to m2
      - run:
          name: run sec test
          shell: /bin/sh
          command: |
            echo "start"
            javac RestCallTest.java
            java RestCallTest
            echo "done"